#!/bin/bash
# This script is targeting CentOS release 6.5
set -e  # Stop on any error

readonly PROGNAME=$(basename $0)
readonly LOG_FILE=$(mktemp /tmp/${PROGNAME}.XXXXXX.log)

# Redirect stdout and stderr to the log file
exec > >(tee -a $LOG_FILE) 2>&1

# Usage
usage () {
	cat <<- EOF
	Usage: $PROGNAME -d <install_directory> -u <mariadb_user> -p <mariadb_password> -s <mariadb_schema>
	
	Installs Magma Classic to the provided directory

	OPTIONS:
	  -d        directory to install magma to
	  -u        mariadb user
	  -p        mariadb password
	  -s        mariadb schema

	Example: $PROGNAME -d ~/ -u magma -p volcano -s Lavabit

	EOF
}

# Process user input
while getopts ":d:u:p:s:" opt; do
    case $opt in
        d)
            export BASE_DIR=$(readlink -m "$OPTARG/magma")
            ;;
        u)
            export MARIADB_USER="$OPTARG"
            ;;
        p)
            export MARIADB_PASSWORD="$OPTARG"
            ;;
        s)
            export MARIADB_SCHEMA="$OPTARG"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument" >&2
            exit 1
            ;;
    esac
done

if [ -z "$BASE_DIR" \
	-o -z "$MARIADB_USER" \
	-o -z "$MARIADB_PASSWORD" \
	-o -z "$MARIADB_SCHEMA" ]; then
	usage
	echo "None of the user input is optional"
	exit 1
fi

export SALT=`echo "$(dd if=/dev/urandom bs=33 count=1 | base64 --wrap=300)"`
export SESSION=`echo "$(dd if=/dev/urandom bs=33 count=1 | base64 --wrap=300)"`

# Check for prerequisites
if [ ! -e /etc/init.d/mariadb ]; then
    echo "Can't find /etc/init.d/mariadb"
    echo "Is MariaDB installed?"
    exit 1
fi

# Rest of your script remains the same, just replace MySQL specific lines with MariaDB ones

# Reset database to factory defaults
scripts/database/schema.init.sh $MARIADB_USER $MARIADB_PASSWORD $MARIADB_SCHEMA


if [ $? -ne 0 ]; then
	echo "Resetting the database failed"
	exit 1
fi

# Generate expected directories
if [ ! -d "$BASE_DIR" ]; then
	mkdir -p "${BASE_DIR}/logs/"
	mkdir -p "${BASE_DIR}/spool/"
	mkdir -p "${BASE_DIR}/storage/"
	mkdir -p "${BASE_DIR}/servers/local/"
fi

# Final step is to put everything in place
cp -rf bin res scripts ${BASE_DIR}/.
mv -f magma.config ${BASE_DIR}/.
