DROP DATABASE IF EXISTS `Sandbox`;
CREATE DATABASE IF NOT EXISTS `Sandbox`;
USE `Sandbox`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
