DROP DATABASE IF EXISTS `trial`;
CREATE DATABASE IF NOT EXISTS `trial`;
USE `trial`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
