DROP DATABASE IF EXISTS `Lavabit`;
CREATE DATABASE IF NOT EXISTS `Lavabit`;
USE `Lavabit`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
